.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. pythonbit_qt test_pythonbit_qt
clean: FORCE
	$(MAKE) -C .. pythonbit_qt_clean test_pythonbit_qt_clean
check: FORCE
	$(MAKE) -C .. test_pythonbit_qt_check
pythonbit-qt pythonbit-qt.exe: FORCE
	 $(MAKE) -C .. pythonbit_qt
